trigger:
  - main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Using a Linux agent

stages:
  # Continuous Integration (CI)
  - stage: BuildAndTest
    displayName: 'Build and Test Node.js Application'
    jobs:
      - job: BuildAndTestJob
        displayName: 'Build and Test Job'
        steps:
          # Step 1: Checkout code from GitHub
          - checkout: self

          # Step 2: Install Node.js (manual or using UseNode@2 if available)
          - script: |
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
              node -v
              npm -v
            displayName: 'Install Node.js'

          # Step 3: Install dependencies
          - script: |
              npm install
            displayName: 'Install Dependencies'

          # Step 4: Run Unit Tests (if tests are available)
          - script: |
              npm test
            displayName: 'Run Unit Tests'

          # Step 5: Publish Test Results
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFiles: '**/test-results.xml'
              testRunTitle: 'Node.js Unit Test Results'

  # Deployment Stages (Optional for Mock Deployment)
  - stage: DeployToDev
    displayName: 'Deploy to Development Environment'
    dependsOn: BuildAndTest
    jobs:
      - job: DeployDevJob
        displayName: 'Deploy Job for Development'
        steps:
          - script: echo "Mock Deploying to Development Environment..."
            displayName: 'Mock Deployment to Dev'

  - stage: DeployToProduction
    displayName: 'Deploy to Production Environment'
    dependsOn: DeployToDev
    jobs:
      - job: DeployProdJob
        displayName: 'Deploy Job for Production'
        steps:
          - script: echo "Mock Deploying to Production Environment..."
            displayName: 'Mock Deployment to Prod'
